chore: publish v1.2.0
supabase/gotrue-dart pull request #107
Opened 2022-11-17 02:07 UTC by dshukertjr

2022-11-17 07:29 UTC, Vinzent03 commented
I read on the Discord that `listUsers` is actually paged so it doesn't return all users. See [gotrue-js issue](https://github.com/supabase/gotrue-js/issues/538). Do we want to fix that before release or remove the method or keep the bug for now?

2022-11-18 04:54 UTC, dshukertjr commented
@Vinzent03 Great find! I was not aware of this at all. I think it's okay to release this for now, and let's implement a feature to get different page once it is implemented on js library!

2022-11-18 07:09 UTC, Vinzent03 requested changes
Okay

2022-11-18 07:09 UTC, Vinzent03 commented on CHANGELOG.md
> +- feat: add `createUser()`, `deleteUser()`, and `listUsers()` to admin methods.
What about adding a link to the pr?

2022-11-18 08:06 UTC, dshukertjr commented on CHANGELOG.md
> +- feat: add `createUser()`, `deleteUser()`, and `listUsers()` to admin methods.
Great catch! Let me add them right now!

2022-11-18 08:16 UTC, Vinzent03 approved these changes

2022-11-18 08:27 UTC, merged

2022-12-17 01:09 UTC, j4w8n commented
> I read on the Discord that `listUsers` is actually paged so it doesn't return all users. See [gotrue-js issue](https://github.com/supabase/gotrue-js/issues/538). Do we want to fix that before release or remove the method or keep the bug for now?

@Vinzent03 this is now a thing in gotrue-js

https://github.com/supabase/gotrue-js/pull/544

Not yet included in the supabase-js client

2022-12-17 07:57 UTC, Vinzent03 commented
@j4w8n I've already implemented it in #109, but you are right it's not jet released. We might bundle it with #110, but I'm not sure. What do you think @dshukertjr ?

2022-12-17 12:57 UTC, dshukertjr commented
Oh yeah sorry. It slipped by with all the launch week chaos! Will create a PR for a new version launch right now!

2022-12-17 13:08 UTC, dshukertjr commented
@j4w8n A new version containing the update has been published!

2022-12-17 13:14 UTC, j4w8n commented
@dshukertjr yep in gotrue-js. They just haven't bumped the version in supabase-js yet.

2022-12-17 13:18 UTC, dshukertjr commented
@j4w8n You mean gotrue-dart and supabase-flutter, correct? Yup, even though supabase-flutter has not been updated, you can actually run `dart pub upgrade gotrue`. This will update your pubspec.lock and therefore upgrade the underlying gotrue version used in your app!

2022-12-17 13:26 UTC, j4w8n commented
@dshukertjr roger that. I'm a js guy. Just remember Vinzent mentioning this feature a while back, and y'all wanted to wait until the js version was out.

2022-12-17 13:30 UTC, Vinzent03 commented
@j4w8n Oh I remember. Yeah I subscribed to the pr after you sent it in the Discord so I was aware of, but thanks for taking care!