fix: prevent AuthState signedIn with null session
supabase/gotrue-dart pull request #133
Opened 2023-03-29 19:12 UTC by rokk4

## What kind of change does this PR introduce?
If  ` _notifyAllSubscribers `is called before` _saveSession`, then the `session` of the emitted `AuthState` will be `null`, because it uses `_currentSession` which is still `null` if `_saveSession` has not been called.

## What is the current behavior?

With #127 the session of the emitted `AuthState` is `null`.

## What is the new behavior?

Same as before #127 , emitted `AuthState` contains the corresponding session.

## Additional context

2023-03-29 21:46 UTC, Vinzent03 approved these changes
Great catch!

2023-03-29 21:51 UTC, Vinzent03 requested changes

2023-03-29 21:51 UTC, Vinzent03 commented on lib/src/gotrue_client.dart
> +          _currentSession?.user.id != session.user.id);
Seems like a bracket too much

2023-03-30 04:48 UTC, dshukertjr commented on lib/src/gotrue_client.dart
> +          _currentSession?.user.id != session.user.id);
```suggestion
      final shouldEmitEvent = _currentSession == null ||
          _currentSession?.user.id != session.user.id; 
```

2023-03-30 05:07 UTC, dshukertjr commented on lib/src/gotrue_client.dart
> +
```suggestion
      final shouldEmitEvent = _currentSession == null ||
          _currentSession?.user.id != session.user.id; 
```

2023-03-30 05:18 UTC, dshukertjr approved these changes
Thanks for the amazing catch! I have fixed the code format issue. Let me bump the version and do a release right now!

2023-03-30 05:31 UTC, merged